apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-base
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://kubernetes.dev.svc
          - cluster: qa
            url: https://kubernetes.qa.svc
          - cluster: prod
            url: https://kubernetes.prod.svc
  template:
    metadata:
      name: '{{cluster}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/Miguelluengo/k8sdemos.git
        targetRevision: HEAD
        path: clusters/{{cluster}}/helm
      destination:
        server: '{{url}}'
        namespace: argocd
