apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-helm
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  source:
    repoURL: 'https://metallb.github.io/metallb'
    targetRevision: 0.13.12
    chart: metallb
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
